master
opensoldat/manual-php-archived pull request #1
Opened 2018-01-05 17:45 UTC by XvayS

updated changelogs/version, made some fixes

2018-04-06 22:44 UTC, Shoozza requested changes

2018-04-06 22:44 UTC, Shoozza commented on index.php
> +
Could you please indent with tab instead of space?

2018-04-06 22:44 UTC, Shoozza commented on index.php
>  }
See comment above

2018-04-06 22:44 UTC, Shoozza commented on config.php
> +	static public $version = '1.7.1';
If possible I'd like to use this for 1.7.2 instead of 1.7.1

2018-04-06 22:44 UTC, Shoozza commented on config.php
> +);
Newline at end of file is missing.

2018-04-07 22:29 UTC, XvayS commented on config.php
> +	static public $version = '1.7.1';
Intention of this PR was to update the repository with the change log of the latest officially available Soldat version. Once there will be a change log ready for 1.7.2 - it could be easily added and therefore this line with version number could be updated too

2018-05-16 21:34 UTC, merged